# Generated by Django 6.0.4 on 2026-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='comments_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='followers_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='monetisation_income',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='posts_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='reputation_score',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
