# Generated by Django 6.0.4 on 2026-05-11 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_author_age_author_comments_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique_for_month='created_at')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.DurationField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('na', 'N/A')], default='na', max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='services.author'),
        ),
    ]
